#!/usr/bin/env bash

#TODO 利用ruby模板技术
echo 将一些ruby的设置链入当前系统...

rcroot=$(dirname $0)/../etc
troot=~
files=( irbrc railsrc rails.irbrc )
for f in ${files[@]};do
  file=$rcroot/dot.$f
  if [ -f $file ];then
    if [ ! -f $troot/.$f ];then
      cp $file $troot/.$f
    else
      echo Warn: already exists: $troot/.$f
    fi
  else
    echo No rcfile: $file
  fi
done
echo Importing ${files[@]} into local
