#!/usr/bin/env bash 

#Usage: ./this_script your_ruby_app_path

[ $# -lt 1 ] && echo Usage: $0 path && exit 1
datapath=$1

function check_and_prepend_utf8(){
  [ $# -lt 1 ] && echo Usage: $FUNCNAME afile  && return 1
  file=$1
  #echo ==Handle $f
  if head -1 $f|grep -qi 'utf-8';then
    echo xx Skip file: $f, found utf-8 at first line 
  else
    t=`tempfile`
    echo "#encoding: utf-8" >$t
    cat $f >>$t
    mv -b $t $f
    echo --Append utf-8 into file: $f
  fi
}

for f in `find $datapath -name "*.rb"`;do
  check_and_prepend_utf8 $f
done

echo end ...
